export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_LIST_REMOVE = 'PRODUCT_LIST_REMOVE';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_REQUEST = 'CART_REQUEST';
export const CART_FAIL = 'CART_FAIL';
export const CART_SHIPPING_ADDRESS = 'CART_SHIPPING_ADDRESS';
export const CART_PAYMENT_METHOD = 'CART_PAYMENT_METHOD';
export const CART_EMPTY = 'CART_EMPTY';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAIL = 'USER_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_PROFILE = 'USER_PROFILE';
